export interface Insight {
  slug: string;
  title: string;
  excerpt: string;
  category: "financial-performance" | "strategy" | "sustainability" | "transactions" | "digital" | "leadership";
  date: string;
  readTime: string;
  featured: boolean;
  content: string[];
}

export const categoryLabels: Record<Insight["category"], string> = {
  "financial-performance": "Financial Performance",
  "strategy": "Strategy",
  "sustainability": "Sustainability",
  "transactions": "Transactions",
  "digital": "Digital",
  "leadership": "Leadership",
};

export const insights: Insight[] = [
  {
    slug: "cfo-guide-uncertainty",
    title: "The CFO's Guide to Navigating Uncertainty: Building Resilient Financial Operations",
    excerpt: "In an era of persistent volatility, CFOs must transform their finance functions from backward-looking scorekeepers to forward-looking strategic partners. This guide outlines the key capabilities required.",
    category: "financial-performance",
    date: "January 2025",
    readTime: "8 min read",
    featured: true,
    content: [
      "The role of the CFO has fundamentally shifted. No longer simply guardians of financial reporting, today's finance leaders are expected to provide real-time insights, model multiple futures, and guide strategic decisions under conditions of profound uncertainty.",
      "## The New Mandate for Finance",
      "Three forces are reshaping expectations for the finance function. First, the velocity of change in markets, regulations, and business models demands faster, more frequent planning cycles. Annual budgets are obsolete before the ink dries. Second, stakeholders—from boards to investors to business unit leaders—expect finance to explain not just what happened, but why it happened and what to do about it. Third, the explosion of available data creates both opportunity and obligation: finance must harness this data or lose relevance to those who will.",
      "## Building Blocks of Resilient Finance",
      "Resilient financial operations rest on four pillars: **dynamic planning**, **predictive analytics**, **agile close processes**, and **strategic business partnering**.",
      "### Dynamic Planning",
      "Replace static annual budgets with continuous planning that incorporates rolling forecasts, driver-based models, and scenario analysis. The goal is not to predict the future—an impossible task—but to prepare for multiple futures and respond rapidly as circumstances evolve.",
      "### Predictive Analytics",
      "Move beyond descriptive reporting (what happened) to diagnostic (why it happened), predictive (what will happen), and ultimately prescriptive analytics (what to do about it). This progression requires investment in data infrastructure, analytical tools, and—critically—talent with the skills to extract insight from data.",
      "### Agile Close Processes",
      "Compress the financial close to free capacity for analysis and decision support. Best-in-class organizations close their books in three to five days, compared to the ten to fifteen days typical of their peers. This acceleration comes not from working harder but from eliminating waste, automating routine tasks, and addressing data quality at the source.",
      "### Strategic Business Partnering",
      "Embed finance professionals within business units to provide real-time decision support. The best FP&A teams spend 80% of their time on analysis and business partnering, not data gathering and report production.",
      "## The Path Forward",
      "Transforming finance is not a technology project—though technology is an enabler. It is fundamentally about changing how finance professionals spend their time, what skills they develop, and how they engage with the business. The CFOs who succeed will be those who view uncertainty not as a threat to be managed but as an opportunity to demonstrate finance's strategic value.",
      "Start by honestly assessing your current capabilities against these four pillars. Identify the biggest gaps between where you are and where you need to be. Then sequence investments in process improvement, technology, and talent development to close those gaps systematically.",
      "The finance function that emerges will be leaner, faster, and more valuable than ever before.",
    ],
  },
  {
    slug: "zero-based-budgeting",
    title: "Zero-Based Budgeting: When It Works and When It Doesn't",
    excerpt: "ZBB has experienced a renaissance, but implementation results vary widely. Understanding when and how to apply ZBB determines whether it delivers sustainable savings or organizational trauma.",
    category: "strategy",
    date: "January 2025",
    readTime: "6 min read",
    featured: false,
    content: [
      "Zero-based budgeting (ZBB) promises to eliminate the waste embedded in traditional incremental budgeting. Rather than adjusting last year's budget by a percentage, ZBB requires justifying every expense from zero. In theory, this approach surfaces costs that have accumulated through inertia and realigns spending with current priorities.",
      "## The ZBB Renaissance",
      "After falling out of favor in the 1990s due to its administrative burden, ZBB has returned with force. Private equity firms have embraced it as a tool for driving post-acquisition cost improvements. Consumer goods companies have credited ZBB with funding marketing investments through indirect cost savings. The approach has spread across industries from healthcare to financial services.",
      "## When ZBB Works",
      "ZBB delivers results when several conditions are met. First, there must be **genuine cost accumulation**—organizations with stable structures and limited competitive pressure often accumulate costs that serve historical rather than current needs. Second, **leadership commitment** is essential; ZBB fails when it becomes a finance exercise rather than an enterprise priority. Third, **implementation capacity** must exist to manage the significant effort required.",
      "The approach works best for indirect costs—general and administrative expenses, marketing spend, and other costs not directly tied to production or service delivery. These categories often lack the market discipline that constrains direct costs and therefore offer more opportunity for reduction.",
      "## When ZBB Fails",
      "ZBB struggles in several scenarios. Organizations already operating efficiently may find the exercise yields little savings while consuming enormous time. Companies with high employee engagement may see morale decline as the process is perceived as punitive. Businesses requiring agility may find that the rigidity of detailed cost packages slows decision-making.",
      "## A Balanced Approach",
      "The most effective implementations apply ZBB selectively. Use zero-based thinking for indirect cost categories where accumulated waste is likely. Apply activity-based analysis to understand what drives costs before setting reduction targets. Build in flexibility for costs that must vary with business conditions.",
      "Most importantly, pair cost reduction with reinvestment. The goal is not austerity but reallocation—shifting resources from lower-value to higher-value activities. Organizations that treat ZBB purely as a cutting exercise often find that savings are short-lived as costs creep back.",
      "ZBB is a powerful tool, but like any tool, its value depends on skilled application. Understanding its limitations is as important as understanding its potential.",
    ],
  },
  {
    slug: "esg-reporting",
    title: "ESG Reporting: Moving Beyond Compliance to Competitive Advantage",
    excerpt: "As ESG reporting requirements proliferate, leading companies are discovering that sustainability data can inform strategy, not just satisfy regulators.",
    category: "sustainability",
    date: "December 2024",
    readTime: "7 min read",
    featured: false,
    content: [
      "The ESG reporting landscape is shifting rapidly. What began as voluntary disclosure for reputation-conscious companies has become mandatory in many jurisdictions. The EU's Corporate Sustainability Reporting Directive (CSRD) will require detailed sustainability reporting from thousands of companies. Similar requirements are emerging globally.",
      "## The Compliance Burden",
      "Meeting these requirements demands significant investment. Companies must collect data across complex supply chains, implement new controls and assurance processes, and develop expertise in emerging reporting frameworks. The administrative burden is substantial, and many organizations are scrambling to comply.",
      "## Beyond Box-Checking",
      "However, the most forward-thinking companies recognize that ESG data—properly collected and analyzed—offers strategic value beyond compliance. Understanding your carbon footprint reveals operational efficiency opportunities. Mapping supply chain sustainability highlights concentration risks. Measuring employee engagement predicts retention and productivity.",
      "## Building Strategic ESG Capabilities",
      "Three capabilities distinguish leaders from laggards in ESG reporting:",
      "### Integrated Data Architecture",
      "Rather than treating ESG as a separate reporting silo, leading organizations integrate sustainability data with financial and operational data. This integration enables analysis of relationships—how does energy efficiency correlate with operating margins? Which suppliers create both cost and sustainability risk?",
      "### Materiality-Focused Disclosure",
      "Not all ESG topics are equally relevant to every business. Effective reporting focuses on material issues—those that affect enterprise value or reflect significant impacts on stakeholders. This focus prevents reporting from becoming an undifferentiated data dump.",
      "### Decision-Relevant Metrics",
      "The best ESG metrics are those that inform decisions. Leading companies develop internal sustainability metrics tied to business drivers, then translate these into external disclosures. This approach ensures that reporting reflects genuine performance rather than check-box compliance.",
      "## The Competitive Advantage",
      "Companies that build these capabilities early will have advantages as ESG factors increasingly influence capital allocation, customer choice, and talent attraction. They will also be better prepared as reporting requirements inevitably expand and intensify.",
      "The investment required is significant, but the alternative—treating ESG as a pure compliance burden—is a missed opportunity. Sustainability data, properly leveraged, can become a source of insight and competitive advantage.",
    ],
  },
  {
    slug: "ma-integration",
    title: "M&A Integration: The First 100 Days That Define Success",
    excerpt: "Most acquisitions fail to deliver expected value, and integration execution is often the culprit. What happens in the first 100 days sets the trajectory for success or disappointment.",
    category: "transactions",
    date: "December 2024",
    readTime: "9 min read",
    featured: false,
    content: [
      "The statistics are sobering: studies consistently show that 50-70% of acquisitions fail to deliver their expected value. While deal thesis, valuation, and due diligence all matter, the most common point of failure is integration execution. The first 100 days after close are particularly critical—patterns established early tend to persist.",
      "## Day One Readiness",
      "Integration planning must begin well before close, not after. The moment the deal closes, employees, customers, and suppliers are watching to see how the combined organization will operate. Confusion or chaos on Day One signals trouble ahead.",
      "Effective Day One planning addresses practical necessities: access to systems, reporting relationships, decision rights, and communication plans. It also addresses symbolic actions that signal the combined organization's direction and values.",
      "## The 100-Day Sprint",
      "The first 100 days should focus on three priorities: **securing the base**, **capturing quick wins**, and **building integration momentum**.",
      "### Securing the Base",
      "Protect the ongoing business. Customer-facing operations must continue without disruption. Key employees—particularly those with critical knowledge or relationships—must be retained. Supply chain and operational continuity must be assured. These are not integration activities per se, but their failure will doom the integration regardless of other efforts.",
      "### Capturing Quick Wins",
      "Early synergy capture builds credibility and funds ongoing integration investments. Focus on procurement savings, elimination of duplicate costs, and revenue opportunities that can be realized quickly. These wins demonstrate that the deal thesis is achievable and maintain organizational energy for harder work ahead.",
      "### Building Integration Momentum",
      "Use the first 100 days to establish integration governance, resolve organizational design questions, and begin cultural integration. Early decisions on structure and leadership cascade through the organization; delays create uncertainty that paralyzes action.",
      "## Common Pitfalls",
      "Several patterns predict integration failure. **Inadequate resources** reflect underestimation of integration complexity. **Retention failures** of key people often result from delayed or inadequate attention to talent. **Culture clashes** emerge when organizations move to merge operations without addressing underlying differences in how work gets done.",
      "## The Role of Leadership",
      "Integration is a leadership challenge as much as an operational one. Leaders must be visible, communicate relentlessly, and make decisions quickly even with imperfect information. The cost of delay almost always exceeds the cost of occasional wrong decisions that can be corrected.",
      "The first 100 days won't complete the integration, but they will determine whether the integration succeeds. Organizations that approach this period with appropriate urgency, resources, and leadership attention dramatically improve their odds of capturing the value that justified the deal.",
    ],
  },
  {
    slug: "digital-transformation-finance",
    title: "Digital Transformation in Finance: Separating Hype from Value",
    excerpt: "Finance functions are under pressure to digitalize, but many initiatives fail to deliver promised returns. A pragmatic approach focuses on business outcomes, not technology for its own sake.",
    category: "digital",
    date: "November 2024",
    readTime: "7 min read",
    featured: false,
    content: [
      "The pressure to digitalize finance is intense. Vendors promise AI-powered insights, robotic process automation, and real-time analytics. Consultants warn of disruption and obsolescence. Yet many digital initiatives in finance fail to deliver expected returns, leaving organizations with expensive technology investments and limited improvement in actual capabilities.",
      "## The Hype Cycle",
      "Finance technology follows a predictable pattern. New capabilities emerge—cloud computing, machine learning, process automation—accompanied by inflated expectations. Early adopters achieve mixed results. Eventually, realistic applications emerge that deliver genuine value.",
      "The challenge for finance leaders is distinguishing between technologies that have reached practical maturity and those still in the hype phase. Investing too early means serving as an unpaid beta tester; investing too late means falling behind more agile competitors.",
      "## A Pragmatic Framework",
      "Successful digital transformation in finance follows several principles:",
      "### Start with Problems, Not Technologies",
      "Identify specific pain points—slow close cycles, inaccurate forecasts, manual reconciliations—then evaluate which technologies address those problems. Technology-led initiatives that seek applications for solutions invariably disappoint.",
      "### Sequence for Value",
      "Not all opportunities are equal. Prioritize initiatives that address significant pain, are technically feasible, and require manageable organizational change. Build momentum with early wins before tackling transformational projects.",
      "### Fix Processes Before Automating",
      "Automating a broken process produces broken results faster. Process improvement should precede or accompany automation. The most successful RPA implementations, for example, begin with process standardization and exception reduction.",
      "### Build Data Foundations",
      "Advanced analytics and AI require quality data. Many organizations underinvest in data architecture, governance, and quality in their rush to deploy analytical tools. The result is sophisticated models producing unreliable outputs.",
      "## Where Value Exists Today",
      "Several finance technology applications have reached practical maturity. Cloud-based planning and consolidation platforms offer faster implementation and lower maintenance than legacy systems. Process automation delivers proven returns for high-volume, rules-based transactions. Advanced analytics add value for organizations with quality data and analytical talent.",
      "Other technologies remain earlier in their development. AI-powered forecasting shows promise but requires significant customization. Blockchain applications in finance remain largely experimental. Natural language processing for financial analysis is improving but not yet reliable for critical applications.",
      "## The Human Element",
      "Technology transformation ultimately succeeds or fails based on people. Finance professionals must develop new skills—data analysis, technology evaluation, change management. Leaders must create cultures that embrace experimentation and tolerate failure. Organizations must balance automation's efficiency gains against the risk of losing critical knowledge as experienced professionals depart.",
      "Digital transformation in finance is neither optional nor straightforward. Success requires pragmatic technology selection, disciplined implementation, and sustained attention to the human factors that determine whether technology investments translate into capability improvements.",
    ],
  },
  {
    slug: "building-high-performance-fpa",
    title: "Building a High-Performance FP&A Function",
    excerpt: "The best FP&A teams are strategic partners to the business, not report factories. Building this capability requires transformation across people, processes, and technology.",
    category: "financial-performance",
    date: "November 2024",
    readTime: "8 min read",
    featured: false,
    content: [
      "Financial Planning & Analysis (FP&A) sits at the intersection of finance and strategy. At its best, FP&A provides insights that shape business decisions and drives performance improvement. Too often, however, FP&A teams are consumed by report production and data gathering, leaving little time for the analysis and business partnering that creates value.",
      "## The FP&A Maturity Spectrum",
      "FP&A functions operate at different levels of maturity. At the basic level, teams produce standard reports on schedule but add little insight beyond the numbers. At the intermediate level, teams provide analysis of variances and trends, helping business leaders understand what happened and why. At the advanced level, teams serve as true business partners—embedded in decision-making, providing forward-looking insights, and actively shaping strategy.",
      "## Barriers to Advancement",
      "Several factors trap FP&A teams at lower maturity levels. **Data fragmentation** forces analysts to spend time gathering and reconciling data from multiple sources. **Manual processes** consume capacity that should go to analysis. **Talent gaps** leave teams without the analytical and communication skills required for business partnering. **Organizational dynamics** sometimes position FP&A as a control function rather than a strategic partner.",
      "## The Transformation Agenda",
      "Moving up the maturity spectrum requires coordinated action across several dimensions:",
      "### Talent",
      "High-performance FP&A requires people who combine financial acumen with business understanding, analytical skills, and the ability to communicate insights effectively. This combination is rare; organizations must either develop these capabilities internally or recruit from diverse backgrounds.",
      "### Process",
      "Streamline and automate routine processes to free capacity for value-added work. Implement self-service reporting so that standard information requests don't consume analyst time. Redesign planning processes to emphasize insight over precision.",
      "### Technology",
      "Modern planning platforms, data visualization tools, and analytical capabilities enable FP&A to work more efficiently and effectively. Technology selection should follow process design—automate optimized processes, not current inefficiencies.",
      "### Operating Model",
      "Define FP&A's role clearly. Who are the customers? What decisions should FP&A inform? How should FP&A time be allocated across reporting, analysis, and business partnering? Embed FP&A professionals within business units while maintaining connection to the corporate finance function.",
      "## Measuring Progress",
      "Track both activity and outcome metrics. Activity metrics—time allocation across reporting, analysis, and business partnering—indicate whether the function is shifting toward higher-value work. Outcome metrics—forecast accuracy, planning cycle time, stakeholder satisfaction—indicate whether the function is delivering value.",
      "## The Investment Case",
      "Building high-performance FP&A requires investment in talent, technology, and transformation effort. The return comes through better decisions—investments that create more value, costs avoided through early warning, strategies adjusted based on rigorous analysis. These returns are difficult to measure precisely but substantial in aggregate.",
      "Organizations that invest in FP&A capability consistently outperform those that view finance as a back-office function. In an environment of increasing uncertainty and competitive intensity, the strategic value of insight-driven decision-making has never been higher.",
    ],
  },
  {
    slug: "restructuring-playbook",
    title: "The Restructuring Playbook: Acting Decisively in Distress",
    excerpt: "When financial distress strikes, speed and decisiveness separate successful turnarounds from failed interventions. A structured approach helps management teams navigate crisis effectively.",
    category: "transactions",
    date: "October 2024",
    readTime: "10 min read",
    featured: false,
    content: [
      "Financial distress demands a different playbook than normal operations. The comfortable pace of strategic planning gives way to urgent cash management. The careful consensus-building of healthy organizations yields to decisive action. Leaders who thrive in stable environments may struggle to adapt their approach when survival is at stake.",
      "## Recognizing Distress",
      "Distress often develops gradually before manifesting suddenly. Warning signs include deteriorating cash conversion, increasing reliance on credit facilities, stretched payment terms with suppliers, and declining sales momentum. By the time these symptoms become acute, the range of available responses has narrowed significantly.",
      "## The First 72 Hours",
      "When distress crystallizes into crisis, the first 72 hours establish the foundation for response. Three priorities dominate:",
      "### Cash Visibility",
      "Immediately establish clear visibility into cash position and near-term cash flows. Many distressed companies cannot answer the basic question: how much cash do we have, and how long will it last? A detailed 13-week cash flow forecast becomes the central management tool.",
      "### Stakeholder Management",
      "Identify key stakeholders—lenders, suppliers, customers, employees—and their likely responses to distress. Communication must be carefully managed; premature disclosure can precipitate crises that might otherwise be avoided, while concealment destroys credibility when eventually discovered.",
      "### Decision Rights",
      "Clarify who has authority to make decisions in the crisis. Normal approval processes are too slow; decisions that previously required extensive review must be made quickly by those with appropriate authority and information.",
      "## Stabilization",
      "With the immediate crisis managed, attention shifts to stabilization. Cash conservation measures—freezing discretionary spending, accelerating collections, stretching payables—buy time. Operational triage identifies which parts of the business are viable and which are not. Quick wins in working capital management often release surprisingly significant cash.",
      "## Restructuring Options",
      "The range of restructuring options depends on the severity of distress and stakeholder positions. Operational restructuring—cost reduction, asset sales, business model changes—may be sufficient for mild distress. Financial restructuring—debt renegotiation, equity infusion, debt-for-equity conversion—becomes necessary when the capital structure is unsustainable. Formal insolvency proceedings represent a last resort but sometimes offer the only path to preserving value.",
      "## The Role of Advisors",
      "External advisors bring experience, credibility, and capacity that distressed organizations typically lack internally. Restructuring advisors have navigated similar situations and understand stakeholder dynamics. Their independence can facilitate negotiations that management alone could not accomplish. However, advisors supplement rather than replace management leadership; owners of the problem must remain engaged.",
      "## Recovery and Learning",
      "Successful turnarounds create opportunities for fundamental improvement. The crisis reveals weaknesses that might otherwise have persisted. The urgency enables changes that normal organizational dynamics would resist. Companies that emerge from distress thoughtfully often achieve performance levels they could not have reached on their prior trajectory.",
      "Every distress situation is unique, but patterns recur. Understanding these patterns—and responding with appropriate speed and decisiveness—dramatically improves the odds of successful navigation through financial crisis.",
    ],
  },
  {
    slug: "supply-chain-resilience",
    title: "Building Supply Chain Resilience Without Sacrificing Efficiency",
    excerpt: "Recent disruptions have exposed the fragility of optimized supply chains. Building resilience requires balancing efficiency with flexibility—a tension that demands new approaches.",
    category: "strategy",
    date: "October 2024",
    readTime: "6 min read",
    featured: false,
    content: [
      "The past several years have stress-tested global supply chains as never before. Pandemic disruptions, geopolitical tensions, natural disasters, and logistics bottlenecks revealed the hidden fragility of systems optimized for efficiency above all else. The resulting shortages and delays reminded businesses that cost optimization has limits.",
      "## The Efficiency Trap",
      "Decades of supply chain management focused on eliminating waste: reducing inventory, consolidating suppliers, minimizing buffer capacity. These efforts delivered significant cost savings. They also created systems with minimal slack—systems that functioned well under normal conditions but failed catastrophically when disrupted.",
      "## Rethinking Resilience",
      "Resilience is not simply the opposite of efficiency. Adding inventory everywhere, duplicating all suppliers, and maintaining excess capacity would certainly reduce risk—but at prohibitive cost. The challenge is building targeted resilience where it matters most while maintaining efficiency elsewhere.",
      "## A Framework for Balance",
      "Three principles guide effective resilience building:",
      "### Risk Segmentation",
      "Not all products, components, and suppliers carry equal risk. Segment the supply base by criticality (impact of disruption) and vulnerability (likelihood of disruption). Concentrate resilience investments on high-criticality, high-vulnerability segments.",
      "### Structural Flexibility",
      "Design supply chains that can adapt to disruption. Dual or multi-sourcing for critical components provides alternatives when primary sources fail. Regional manufacturing presence reduces exposure to logistics disruptions. Modular product designs enable substitution when specific components are unavailable.",
      "### Visibility and Response",
      "Invest in visibility across the extended supply chain. Early warning of emerging disruptions enables proactive response. Real-time visibility into inventory positions and in-transit shipments supports dynamic reallocation when disruptions occur.",
      "## The Cost of Resilience",
      "Building resilience carries costs. Buffer inventory ties up working capital. Supplier diversification may forfeit volume discounts. Regional manufacturing presence may face higher labor costs than consolidated operations. These costs must be weighed against the costs of disruption—not just direct costs but also customer defection, reputation damage, and competitive disadvantage.",
      "## Moving Forward",
      "The pendulum has swung from pure efficiency toward greater resilience, but the optimal balance differs by industry, product, and competitive context. Companies that develop sophisticated approaches to this tradeoff—rather than swinging between extremes—will build supply chains that are both efficient and robust.",
      "The supply chain disruptions of recent years were neither the first nor the last. Building resilience is not a one-time project but an ongoing capability that must evolve as risks change.",
    ],
  },
];

export function getFeaturedInsight() {
  return insights.find((i) => i.featured) || insights[0];
}

export function getRecentInsights(count: number = 3, excludeSlug?: string) {
  return insights
    .filter((i) => i.slug !== excludeSlug)
    .slice(0, count);
}

export function getInsightBySlug(slug: string) {
  return insights.find((i) => i.slug === slug);
}

export function getInsightsByCategory(category: Insight["category"]) {
  return insights.filter((i) => i.category === category);
}
